albuns/urls.py
from django.urls import path

from . import views
from .views import PostDetailView, PostListView,  PostSearchView, PostCreateView, PostUpdateView,PostDeleteView, PostDetailView



app_name = 'albuns'
urlpatterns = [
    #path('', views.list_albuns, name='index'),
    path('albuns/', PostListView.as_view(), name='index'),

    #path('search/', views.search_albuns, name='search'),
    path('albuns/search/', PostSearchView.as_view(), name='search'),

    #path('create/', views.create_album, name='create'),
    path('albuns/create/', PostCreateView.as_view(), name='create'),

    #path('<int:album_id>/', views.detail_album, name='detail'),
    path('albuns/<int:album_id>/', PostDetailView.as_view(), name='detail'),
    
    #path('update/<int:album_id>/', views.update_album, name='update'),
    path('albuns/<int:pk>/update/', PostUpdateView.as_view(), name='update'),

    #path('delete/<int:album_id>/', views.delete_album, name='delete'),
    path('albuns/<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),

    path('albuns/<int:post_id>/comment/', views.create_comment, name='comment'),

    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category-posts/<int:category_id>/', views.CategoryPostsListView.as_view(), name='category-posts'),
    path('albuns/category-post-detail/<int:category_id>/<int:pk>/', views.CategoryPostDetailView.as_view(), name='category-post-detail'),
    path('albuns/<int:album_id>/', views.PostDetailView.as_view(), name='detail'),
]

discosite/urls.py
from django.contrib import admin
from django.urls import include, path # modificar esta linha

urlpatterns = [
    path('', include('staticpages.urls')),
    path('albuns/', include('albuns.urls')),
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

albuns/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField(default="")
    post_date = models.DateTimeField(default=timezone.now)
    
    band = models.CharField(max_length=30)
    release_year = models.IntegerField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.title} ({self.release_year})'
    



class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username} em {self.post.title}'
    
class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}: {self.description}'

albuns/forms.py
from django import forms


from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'release_year',
            'poster_url',
            'content',
            'band',

        ]
        labels = {
            'title': 'Título',
            'release_year': 'Data de Lançamento',
            'poster_url': 'URL do Poster',
            'content': 'Descrição',
            'band': 'Artista',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

albuns/views.py
from django.shortcuts import render

from django.http import HttpResponse
from .temp_data import album_data
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.urls import reverse_lazy
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

class PostListView(ListView):
    model = Post
    template_name = 'albuns/index.html'
    context_object_name = 'album_list'


class PostDetailView(DetailView):
    model = Post
    template_name = 'albuns/detail.html'
    context_object_name = 'album'
    pk_url_kwarg = 'album_id'


class PostSearchView(ListView):
    model = Post
    template_name = 'albuns/search.html'
    context_object_name = 'album_list'

    def get_queryset(self):
        query = self.request.GET.get('query', '')
        if query:
            return Post.objects.filter(title__icontains=query.lower())
        else:
            return Post.objects.none()
        

class PostCreateView(CreateView): 
    model = Post
    form_class = PostForm
    template_name = 'albuns/create.html'
    success_url = reverse_lazy('albuns:create')

    def form_valid(self, form):
        response = super().form_valid(form)
        # Após criar o post, redirecione para os detalhes do post recém-criado
        return HttpResponseRedirect(reverse('albuns:detail', args=(self.object.id,)))


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'albuns/update.html'
    context_object_name = 'album'

    def get_success_url(self):
        return reverse_lazy('albuns:detail', args=(self.object.id,))


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'albuns/delete.html'
    context_object_name = 'album'
    success_url = reverse_lazy('albuns:index')

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('albuns:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    #return HttpResponseRedirect(reverse('albuns:detail', args=(post_id,)))
    return render(request, 'albuns/comment.html', context)


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'albuns/category.html'
    context_object_name = 'category_list'

class CategoryPostsListView(generic.ListView):
    template_name = 'albuns/index.html'
    context_object_name = 'post_list'

    def get_category(self):
        return Category.objects.get(pk=self.kwargs['category_id'])

    def get_queryset(self):
        return self.get_category().posts.all()
    
    def get_context_data(self, **kwargs):
        category = self.get_category()
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Categoria'
        context['albumpage_title'] = f'Categoria {category.name}'
        context['category'] = True
        context['category_id'] = category.id
        return context
    
class CategoryPostDetailView(generic.DetailView):
    model = Post
    template_name = 'albuns/detail.html'

    def get_object(self):
        category_id = self.kwargs.get('category_id')
        pk = self.kwargs.get('pk')
        category = Category.objects.get(pk=category_id)
        posts = category.posts.all()
        post = get_object_or_404(posts, pk=pk) 
        return post

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

albuns/templates/albuns/category.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de albuns</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <h3>{{category.name}}</h3>
            
            Descrição: {{category.description}}
        </header>
        
        <div class="lista-de-cards">
            {% for post in category.posts.all %}
            <div class="card">
                <a href="{% url 'albuns:detail' post.id %}">
                    <img src="{{ post.poster_url }}" alt="Imagem de {{ post.title}}">
                </a>
                <p>{{ post.title }}</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}
</section>

{% endblock content %}

albuns/templates/albuns/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Álbum {{ album.name }} ({{ album.release_year }})</h2>

<form action="{% url 'albuns:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'albuns:detail' post.id %}">Voltar para a página do álbum</a></p>
{% endblock content %}

albuns/templates/albuns/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Álbum</h2>
<form method="post" action="{% url 'albuns:create' %}">
    {% csrf_token %}
    {{ form.as_p }} <!-- Django converte essa linha para label/input...-->
    <button type="submit">Criar</button>
</form>

{% endblock content %}

albuns/templates/albuns/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'albuns:delete' album.id %}" method="post">
  {% csrf_token %}
  <p>
    Você tem certeza que deseja apagar o filme "{{ album.title }} "?
  </p>
  <button type="submit">Apagar</button>
</form>
{% endblock content %}

albuns/templates/albuns/detail.html
{% extends 'base.html' %} {% block title %} {{ album.title }} ({{
    album.release_year }} {% endblock title %} {% block content %}
    <h2>Detalhes do Álbum {{ album.title }} ({{ album.release_year }})</h2>
    
    <section class="dados-de-filme"> <!--deixar como dados de filme para usar css-->
      <img src="{{ album.poster_url }}" alt="Poster do Álbum {{ album.title}}" />
      <ul>
        <li>Título: {{ album.title }}</li>
        <li>Ano de Lançamento: {{ album.release_year }}</li>
        <li>Artista: {{ album.band }}</li>
        <li>Descrição: {{ album.content }}</li>
        
        <hr>
        <li><a href="{% url 'albuns:update' album.id %}">Editar</a></li>
    <li><a href="{% url 'albuns:delete' album.id %}">Apagar</a></li>
        <hr>
        <li>Data de postagem: {{ album.post_date }}</li>
        
      </ul>
    </section>

    <section> 
    {% if album.category_set.all %}
        <li><strong>Incluso nas categorias:</strong> {{ album.category_set.all|join:", " }} </li>
    {% endif %}
        


    </section>

    <section>
      <header>
          <h3>Comentários</h3>
      </header>
      <ul>
          {% if album.comment_set.all %}
              {% for comment in album.comment_set.all %}
                  <figure>
                      <blockquote>
                          "{{ comment.text }}"
                      </blockquote>
                      <figcaption>—{{ comment.author }}</figcaption>
                  </figure>
              {% endfor %}
          {% else %}
              <p>Ainda não existe nenhuma comentário para este álbum.</p>
          {% endif %}
      </ul>
      <hr>
      <a href="{% url 'albuns:comment' album.pk %}"><button>Crie sua Resenha</button></a>
  
  </section>
    
    {% endblock content %}

albuns/templates/albuns/index.html
{% extends 'base.html' %} {% block content %}
<h2>Todos os Álbuns</h2>

<section>
    <p>
      Muitos resultados? <a href="{% url 'albuns:search' %}">Buscar Álbuns</a>
    </p>
    <p>
      Não encontrou o Álbum?
      <a href="{% url 'albuns:create' %}">Adicionar Novo Álbum</a>
    </p>
  </section>

{% if album_list %}
<section class="lista-de-cards">
  {% for album in album_list %}
  <article class="card">
    <a href="{% url 'albuns:detail' album.id %}">
      ><img src="{{ album.poster_url }}" alt="Poster do Álbum {{ album.title}}"
    /></a>
    <p>{{ album.title }} ({{ album.release_year }})</p>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum Álbum.</p>
{% endif %} {% endblock content %}

albuns/templates/albuns/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Álbuns por Nome</h2>
<form action="{% url 'albuns:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if album_list %}
<section class="lista-de-cards">
    {% for album in album_list %}
    <article class="card">
        <img src="{{ album.poster_url }}" alt="Poster do Álbum {{ album.title}}">
        <p>{{ album.title }} ({{ album.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum Álbum para a busca.</p>
{% endif %}

{% endblock content %}

albuns/templates/albuns/update.html
{% extends 'base.html' %}
{% block content %}
<h2>Atualizar Dados do Filme {{ album.title }} ({{ album.release_year}})</h2>
<form method="post" action="{% url 'albuns:update' album.id%}">
  {% csrf_token %}
  <p>
    <label for="id_title">Título:</label>
    <input type="text" name="title" id="id_title" />
  </p>
  <p>
    <label for="id_band">Artista:</label>
    <input type="text" name="band" id="id_band" />
  </p>
  <p>
    <label for="id_release_year">Ano de Lançamento:</label>
    <input type="number" name="release_year" id="id_release_year" />
  </p>
  <p>
    <label for="id_content">Descrição:</label>
    <input type="text" name="content" id="id_content" />
  </p>
  <p>
    <label for="id_poster_url">URL do Poster:</label>
    <input type="url" name="poster_url" id="id_poster_url" />
  </p>
  <button type="submit">Atualizar</button>
</form>
{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>


Bem-vindo ao Escute essa música!, o seu destino definitivo para explorar e celebrar a vasta paisagem musical através das décadas. Aqui, mergulhamos nas nuances e encantos dos álbuns que moldaram gerações, criaram movimentos culturais e deixaram uma marca indelével na história da música. Seja você um ávido melômano ou alguém que está apenas começando a explorar os acordes da vida, nosso site é o seu guia confiável para descobrir, compartilhar e apreciar o universo infinito da música.
<hr>
Aqui acreditamos que a música é mais do que uma simples combinação de notas; é uma jornada emocional, uma narrativa que transcende o tempo. Nossa comunidade é alimentada pela paixão compartilhada por álbuns que nos fazem vibrar, refletir, dançar e, acima de tudo, sentir. Aqui, cada página é uma homenagem a essas obras-primas sonoras que resistiram ao teste do tempo e continuam a inspirar gerações.
<hr>
Explore as resenhas de álbuns escritas por nossa comunidade diversificada de entusiastas musicais, descubra novas pérolas escondidas e reviva clássicos que definiram momentos inesquecíveis em suas vidas. Este é mais do que um site; é um santuário para todos aqueles que encontram significado, consolo e alegria na linguagem universal da música.
<hr>
Prepare-se para uma viagem única, onde cada página é uma porta de entrada para o extraordinário mundo dos álbuns atemporais. Embarque conosco nesta jornada musical, onde a melodia se encontra com a memória, e cada resenha é uma celebração do eterno poder da música. Este é o seu convite para se perder nas batidas, harmonias e letras que moldaram eras - bem-vindo ao Escute essa música.
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Escute essa música!</i></h1>
<p>A Página para Comunidade Resenhadora de Músicas</p>
{% endblock content %}

templates/base.html
{% load static %} <!-- adicione esta linha -->
<style>
    /* Estilo para o contêiner <logo> */
    a.logo {
        display: inline-block; /* Certifica-se de que o link é tratado como bloco */
        width: 200px; /* Largura desejada */
        height: 100px; /* Altura desejada */
        /* Adicione mais estilos conforme necessário */
    }

    /* Estilo para a imagem dentro do link */
    a.logo img {
        width: 100%; /* A imagem ocupa 100% da largura do contêiner <a> */
        height: 100%; /* A imagem ocupa 100% da altura do contêiner <a> */
        /* Adicione mais estilos conforme necessário */
    }
</style>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Escute essa música!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">

        <a class = logo href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul>
              <li><a href="{% url 'albuns:index' %}">Álbuns</a></li>
              <li><a href="{% url 'albuns:category' %}">Categorias</a></li> 

              <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
          </nav>
    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2023 - Feito por Vítor Kassab</small>
        </p>
    </footer>
</body>

</html>